### ISSUE TITLE
feature: 如果编辑器已经打开了i18n文件，点击跳转时可以不需要再次打开，直接聚焦到已打开的文件会体验更好

### ISSUE THREAD

**Issue by Jasery** [Momo707577045/i18n-jump#1]
以下操作会同时打开两个相同的文件

https://user-images.githubusercontent.com/20091279/236756143-4d15cf83-01a6-4046-8326-8f5cf86710f2.mov

期望：直接聚焦到右边的文件

**Comment by Momo707577045** [comment]
感谢反馈，已mr，已更新版本
