### ISSUE TITLE
feature: 添加隐藏"跳转 gitlab"菜单配置

### ISSUE THREAD

**Issue by Jasery** [Momo707577045/i18n-jump#3]
背景：
之前的某个版本添加了“跳转 gitlab”菜单，如下图：
![image](https://github.com/Momo707577045/i18n-jump/assets/20091279/aff1e4c6-1dd5-4c46-8a10-9655f03ed398)

问题：
1. 这个是特定的地址，并不是所有项目都能跳转
2. 个人习惯极少使用这个菜单
3. 当选中的是文件夹时，原本第一个是高频使用的“添加文件”被占据了，肌肉记忆导致经常点错

期望：
1. 希望能添加个配置隐藏这个菜单

**Comment by Momo707577045** [comment]
已合并 pr ，新功能已发布，v0.0.24
